// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcxqyhimrqcjtniyqcut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjeHF5aGltcnFjanRuaXlxY3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjE0ODYsImV4cCI6MjA2Mjc5NzQ4Nn0.8fD5rHkb_OuvTcGHWjlwWV1gk_IIDGf5HA4nQaif03I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);